definitions:
  models.ErrorDetail:
    properties:
      detail:
        type: string
    type: object
  models.HTTPError:
    properties:
      errors:
        items:
          $ref: '#/definitions/models.ErrorDetail'
        type: array
      message:
        type: string
    type: object
  models.UserToken:
    properties:
      token:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Lets a new user register to get a new token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Signup
      tags:
      - user
swagger: "2.0"
